### ISSUE TITLE
How can I add image and save it in Controller?

### ISSUE THREAD

**Issue by KateKati** [kartik-v/yii2-widget-summernote#5]
I can add Image, but then, how will I get in in Controller??? I want to have wisywig editor with images, but no editor for yii2 with images is working, im so desperate, pls help

**Comment by genny3021** [comment]
@KateKati  I just encountered the same 'issue' and I'm sharing my 'solution'

Good news is, there's actually no issue. The editor adds the base64 image and you can't see it because its not properly rendered. I don't know how you're trying to assess it but in detail view, I can view the image with the format 'raw'. Eg
		`
	[
                'attribute'=>'full_desc',
                'format'=>'raw',
                'value' => $model->full_desc
            ],
`

To display the code in a page, use html decode
`<?=Html::decode($model->full_desc)?>`
